services:
  opensearch:
    image: opensearchproject/opensearch:1.2.4
    ports:
      - 9200:9200
      - 9600:9600
    environment:
      discovery.type: single-node
    volumes:
      - opensearch-data:/usr/share/opensearch/data
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.2.0
    ports:
      - 5601:5601
    depends_on:
      - opensearch
    environment:
      OPENSEARCH_HOSTS: https://opensearch:9200

volumes:
  opensearch-data:
