version: '3'

services:
  nexus:
    image: sonatype/nexus3:3.19.1
    restart: always
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data:
