version: '3'

services:
  neo4j:
    image: neo4j:3.5
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: "none"
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data:
