services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - 3000:3000
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      PORT: 3000
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      WEBUI_AUTH: False
      AUDIO_TTS_ENGINE: transformers
    volumes:
      - open-webui-data:/app/backend/data

volumes:
  open-webui-data:
    name: open-webui-data
