services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    network_mode: host
    volumes:
      - open-webui-data:/app/backend/data

volumes:
  open-webui-data:
