version: "3"

services:
  loki:
    image: grafana/loki:2.2.0
    ports:
      - 3100:3100
    command: ["-config.file=/etc/loki/local-config.yaml"]
  promtail:
    image: grafana/promtail:2.2.0
    ports:
      - 9080:9080
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
    command: ["-config.file=/etc/promtail/config.yaml"]
