services:
  loki:
    image: grafana/loki:3.0.0
    ports:
      - 3100:3100
    volumes:
      - ./loki-local-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
  promtail:
    image: grafana/promtail:3.0.0
    ports:
      - 9080:9080
    volumes:
      - ./promtail-docker-config.yaml:/etc/promtail/config.yaml:ro
      - /var/log:/var/log
    command: ["-config.file=/etc/promtail/config.yaml"]

volumes:
  loki-data:
