version: "3"

services:
  loki:
    image: grafana/loki:2.9.2
    ports:
      - 3100:3100
    volumes:
      - loki-data:/loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
  promtail:
    image: grafana/promtail:2.9.2
    ports:
      - 9080:9080
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml:ro
      - /var/log:/var/log
    command: ["-config.file=/etc/promtail/config.yaml"]

volumes:
  loki-data:
