services:
  forgejo-runner:
    image: code.forgejo.org/forgejo/runner:4.0.1
    container_name: forgejo-runner
    user: 0:0
    volumes:
      - forgejo-runner-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - forgejo
    command: >-
      bash -c "
      forgejo-runner create-runner-file --connect --instance ${FORGEJO_INSTANCE} --name runner --secret ${RUNNER_SECRET} ;
      sed -i -e 's|\"labels\": null|\"labels\": [\"ubuntu-latest:docker://catthehacker/ubuntu:act-22.04\"]|' .runner ;
      forgejo-runner generate-config > config.yml ;
      sed -i -e 's|^  network: .*|  network: forgejo|' config.yml ;
      forgejo-runner daemon --config config.yml
      "

volumes:
  forgejo-runner-data:

networks:
  forgejo:
    name: forgejo
    external: true
