services:
  forgejo-runner:
    image: code.forgejo.org/forgejo/runner:5.0.0
    container_name: forgejo-runner
    user: 0:0
    volumes:
      - forgejo-runner-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - forgejo
    command: >-
      bash -c "
      forgejo-runner create-runner-file --connect --instance ${FORGEJO_INSTANCE} --name runner --secret ${RUNNER_SECRET} ;
      sed -i -e 's|\"labels\": null|\"labels\": [\"ubuntu-latest:docker://catthehacker/ubuntu:act-24.04\"]|' .runner ;
      forgejo-runner generate-config > config.yml ;
      sed -i -e 's|^  network: .*|  network: forgejo|' config.yml ;
      sed -i -e 's|^  options:.*|  options: --volume=/var/run/docker.sock:/var/run/docker.sock|' config.yml ;
      sed -i -e 's|^  privileged: .*|  privileged: true|' config.yml ;
      sed -i -e 's|^  valid_volumes: .*|  valid_volumes: [\"**\"]|' config.yml ;
      #sed -i -e 's|^  secret: .*|  secret: zZti23AxqNi89D3IyAea7uov064=|' config.yml ;
      #sed -i -e 's|^  external_server: .*|  external_server: http://github-actions-cache-server:3000/|' config.yml ;
      forgejo-runner daemon --config config.yml
      "

volumes:
  forgejo-runner-data:

networks:
  forgejo:
    name: forgejo
    external: true
