services:
  docker:
    image: docker:dind
    container_name: dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - dind-certs:/certs
      - dind-data:/var/lib/docker
  forgejo-runner:
    image: code.forgejo.org/forgejo/runner:11
    container_name: forgejo-runner
    depends_on:
      docker:
        condition: service_started
    volumes:
      - dind-certs:/certs:ro
      - forgejo-runner-data:/data
    env_file: .env
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: /certs/client
      FORGEJO_INSTANCE: ${FORGEJO_INSTANCE:-http://host.docker.internal:3000}
      RUNNER_NAME: ${RUNNER_NAME:-forgejo-runner}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
    command: >-
      bash -c "
      forgejo-runner register --no-interactive --token $${RUNNER_TOKEN} --name $${RUNNER_NAME} --instance $${FORGEJO_INSTANCE} ;
      sed -i -e 's|\"labels\": null|\"labels\": [\"ubuntu-latest:docker://node:22-bookworm\"]|' .runner ;
      forgejo-runner generate-config > config.yml ;
      sed -i -e 's|^  options:.*|  options: -v /certs/client:/certs/client|' config.yml ;
      sed -i -e 's|^  privileged:.*|  privileged: true|' config.yml ;
      sed -i -e 's|^  valid_volumes: .*|  valid_volumes: [\"**\"]|' config.yml ;
      forgejo-runner daemon --config config.yml
      "

volumes:
  forgejo-runner-data:
  dind-certs:
  dind-data:
