version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    volumes:
      - ./zk-data:/var/lib/zookeeper/data
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka
    restart: always
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - JMX_PORT=9999
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    ports:
      - 9092:9092
      - 9999:9999
    depends_on:
      - zookeeper
  schema-registry:
    image: confluentinc/cp-schema-registry
    restart: always
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
    ports:
      - 8081:8081
    depends_on:
      - kafka
