version: "3"

services:
  soft-serve:
    image: charmcli/soft-serve:v0.1
    environment:
      SOFT_SERVE_HOST: 0.0.0.0
      SOFT_SERVE_PORT: 23231
      SOFT_SERVE_KEY_PATH: ssh/soft_serve_server_ed25519
      SOFT_SERVE_REPO_PATH: repos
      SOFT_SERVE_INITIAL_ADMIN_KEY: ""
    volumes:
      - soft-serve-data:/soft-serve
    ports:
      - "23231:23231"

volumes:
  soft-serve-data:
