version: "3"

services:
  act-runner:
    image: gitea/act_runner:nightly
    networks:
      - gitea
    volumes:
      - act-runner-data:/data
      - ./config.yaml:/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "http://gitea:3000"
      GITEA_RUNNER_NAME: "Gitea Act Runner"

volumes:
  act-runner-data:

networks:
  gitea:
    name: gitea
    external: true
