services:
  openldap:
    image: bitnami/openldap:2
    ports:
      - 389:1389
      - 636:1636
    env_file: .env
    volumes:
      - openldap-data:/bitnami/openldap
  phpldapadmin:
    image: osixia/phpldapadmin:stable
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap:1389
    volumes:
      - phpldapadmin-data:/var/www/phpldapadmin

volumes:
  openldap-data:
  phpldapadmin-data:
