version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.10.0
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: host

volumes:
  prometheus-data:
