version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.29.0
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus/:ro
  alertmanager:
    image: prom/alertmanager:v0.23.0
    restart: always
    ports:
      - 9093:9093
    volumes:
      - alertmanager-data:/alertmanager
      - ./alertmanager:/etc/alertmanager/:ro
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.19.0
    restart: always
    ports:
      - 9115:9115
  node-exporter:
    image: prom/node-exporter:v1.2.2
    restart: always
    network_mode: host
    volumes:
      - /:/host:ro,rslave
    command:
      - "--path.rootfs=/host"

volumes:
  prometheus-data:
  alertmanager-data:
