version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.29.0
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus/:ro
  alertmanager:
    image: prom/alertmanager:v0.23.0
    restart: always
    ports:
      - 9093:9093
    volumes:
      - alertmanager-data:/alertmanager
      - ./alertmanager:/etc/alertmanager/:ro

volumes:
  prometheus-data:
  alertmanager-data:
