version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.26.0
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus/
  alertmanager:
    image: prom/alertmanager:v0.21.0
    restart: always
    ports:
      - 9093:9093
    volumes:
      - alertmanager-data:/alertmanager
      - ./alertmanager:/etc/alertmanager/

volumes:
  prometheus-data:
  alertmanager-data:
