version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.3.1
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: host
