services:
  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus/:ro
  alertmanager:
    image: prom/alertmanager:v0.27.0
    ports:
      - 9093:9093
    volumes:
      - alertmanager-data:/alertmanager
      - ./alertmanager:/etc/alertmanager:ro
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --cluster.listen-address=
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.25.0
    ports:
      - 9115:9115
  node-exporter:
    image: prom/node-exporter:v1.8.2
    network_mode: host
    volumes:
      - /:/host:ro,rslave
    command:
      - --path.rootfs=/host

volumes:
  prometheus-data:
  alertmanager-data:
