version: "3"

services:
  gitea:
    image: gitea/gitea:1-rootless
    restart: always
    ports:
      - 3000:3000
      - 8022:8022
    volumes:
      - gitea-data:/data
    environment:
      DB_TYPE: mysql
      DB_HOST: mariadb:3306
      DB_NAME: gitea
      DB_USER: gitea
      DB_PASSWD: gitea
      SSH_DOMAIN: gitea
      SSH_PORT: 8022
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.5
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

volumes:
  gitea-data:
  mariadb-data:
