services:
  gitea:
    image: gitea/gitea:1-rootless
    container_name: gitea
    networks:
      - gitea
    ports:
      - 3000:3000
      - 8022:8022
    volumes:
      - gitea-config:/etc/gitea
      - gitea-data:/var/lib/gitea
    environment:
      GITEA_DATABASE_DB_TYPE: sqlite

volumes:
  gitea-config:
  gitea-data:

networks:
  gitea:
    name: gitea
