version: '3'

services:
  gitea:
    image: gitea/gitea:1
    restart: always
    ports:
      - 3000:3000
    volumes:
      - gitea-data:/data
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.4
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

volumes:
  gitea-data:
  mariadb-data:
