services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    command: start-dev
    ports:
      - 8080:8080
      - 8443:8443
      - 9000:9000
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: keycloak
    volumes:
      - keycloak-data:/opt/keycloak/data/

volumes:
  keycloak-data:
