services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    hostname: nas
    command: start --hostname localhost
    ports:
      - 8080:8080
      - 8443:8443
      - 9000:9000
    network_mode: host
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: keycloak
      KC_HTTP_ENABLED: "true"
    volumes:
      - keycloak-data:/opt/keycloak/data/

volumes:
  keycloak-data:
