version: "3"

services:
  keycloak:
    image: keycloak/keycloak:23.0.7
    restart: always
    command: start-dev --proxy edge
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-config:/config
      - caddy-data:/data

volumes:
  caddy-config:
  caddy-data:
