version: "3"

services:
  keycloak:
    image: jboss/keycloak:14.0.0
    restart: always
    ports:
      - 8180:8080
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
    volumes:
      - ./startup-scripts:/opt/jboss/startup-scripts/:ro
