version: '2'

services:
  keycloak:
    image: jboss/keycloak:4.0.0.Final
    restart: always
    ports:
      - 8180:8080
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=mariadb
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.2
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
