version: '2'

services:
  keycloak:
    image: jboss/keycloak:3.4.3.Final
    restart: always
    ports:
      - 8180:8080
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=cloakpass
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
    depends_on:
      - mysql
  mysql:
    image: mysql:5
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=cloakpass
      - MYSQL_ROOT_PASSWORD=masterpass
