version: "3"

services:
  grafana:
    image: grafana/grafana:8.0.0
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: grafana
      GF_SECURITY_ADMIN_PASSWORD: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    network_mode: host

volumes:
  grafana-data:
