version: "3"

services:
  grafana:
    image: grafana/grafana:10.1.5
    environment:
      GF_SECURITY_ADMIN_USER: grafana
      GF_SECURITY_ADMIN_PASSWORD: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    network_mode: host

volumes:
  grafana-data:
