version: '3'

services:
  graphite:
    image: graphiteapp/graphite-statsd:1.1.5-10
    restart: always
    ports:
      - 8000:80
      - 2003:2003
      - 2004:2004
      - 2023:2023
      - 2024:2024
      - 8125:8125/udp
      - 8126:8126
    volumes:
      - graphite-data:/opt/graphite/storage

volumes:
  graphite-data:
