version: "3"

services:
  trivy:
    image: aquasec/trivy:0.19.2
    volumes:
      - trivy-data:/root/.cache
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["alpine:3.14.0"]

volumes:
  trivy-data:
