version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
  logstash:
    image: logstash:alpine
    command: logstash -f /etc/logstash/logstash.conf
    ports:
      - 9600:9600
    volumes:
      - ./logstash.conf:/etc/logstash/logstash.conf
    links:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.0
    ports:
      - 5601:5601
    links:
      - elasticsearch
