version: '3'

services:
  zookeeper:
    image: zookeeper:3.7
    restart: always
    ports:
      - 2181:2181
    volumes:
      - zk-data:/data
      - zk-datalog:/datalog
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    restart: always
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_LISTENERS: PLAINTEXT://:9092,SASL_PLAINTEXT://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092,SASL_PLAINTEXT://:9093
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_CREATE_TOPICS: "test:2:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka-broker_jaas.conf"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
    volumes:
      - kafka-data:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-broker_jaas.conf:/etc/kafka/kafka-broker_jaas.conf
    depends_on:
      - zookeeper

volumes:
  zk-data:
  zk-datalog:
  kafka-data:
