version: '3'

services:
  zookeeper:
    image: zookeeper:3.5
    ports:
    - 2181:2181
    network_mode: host
  kafka:
    image: wurstmeister/kafka:1.1.0
    ports:
    - 9092:9092
    - 9093:9093
    environment:
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,SASL_PLAINTEXT://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,SASL_PLAINTEXT://localhost:9093
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_CREATE_TOPICS: "test:2:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      CUSTOM_INIT_SCRIPT: "export KAFKA_OPTS=\"-Djava.security.auth.login.config=/etc/kafka/kafka-broker_jaas.conf\""
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
    volumes:
    - kafka-data:/kafka
    - ./kafka-broker_jaas.conf:/etc/kafka/kafka-broker_jaas.conf
    depends_on:
    - zookeeper
    network_mode: host

volumes:
  kafka-data:
