version: "3"

services:
  minidlna:
    image: vladgh/minidlna:0
    ports:
      - 8200:8200
    environment:
      MINIDLNA_MEDIA_DIR_1: A,/media/audio
      MINIDLNA_MEDIA_DIR_2: P,/media/pictures
      MINIDLNA_MEDIA_DIR_3: V,/media/video
      MINIDLNA_FRIENDLY_NAME: Docker
    volumes:
      - ~/Music:/media/audio
      - ~/Pictures:/media/pictures
      - ~/Video:/media/video
      - minidlna-data:/var/lib/minidlna

volumes:
  minidlna-data:
