version: '3'

services:
  jenkins:
    build: .
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
      - ./init.groovy.d:/usr/share/jenkins/ref/init.groovy.d/

volumes:
  jenkins-data:
