services:
  otel-collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.131.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    configs:
      - source: otel-collector-config
        target: /etc/otel-collector-config.yaml
    ports:
      - 1888:1888
      - 4317:4317
      - 4318:4318
      - 8888:8888
      - 8889:8889
      - 13133:13133
      - 55679:55679

configs:
  otel-collector-config:
    content: |
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      processors:
        batch:

      exporters:
        debug:

      extensions:
        health_check:
        pprof:
        zpages:

      service:
        extensions: [health_check, pprof, zpages]
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug]
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug]
