version: '3'

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss
    ports:
    - 8081:8081
    volumes:
    - ./data:/var/opt/jfrog/artifactory
    - ./conf:/artifactory_extra_conf/
