services:
  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    ports:
      - 8081:8081
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory
      - ./conf:/artifactory_extra_conf/

volumes:
  artifactory-data:
