version: "3"

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:7.27.9
    ports:
      - 8081:8081
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory
      - ./conf:/artifactory_extra_conf/

volumes:
  artifactory-data:
