version: '3'

services:
  portainer:
    image: portainer/portainer:1.17.1
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
