version: '3'

services:
  portainer:
    image: portainer/portainer:1.19.2
    restart: always
    ports:
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer-data:/data

volumes:
  portainer-data:
