version: '3'

services:
  jupyterhub:
    build: .
    ports:
    - 8000:8000
    - 8081:8081
    volumes:
    - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - jupyterhub

networks:
  jupyterhub:
