version: "3"

services:
  wikijs:
    image: requarks/wiki:2
    environment:
      DB_TYPE: mariadb
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: wikijs
      DB_PASS: wikijs
      DB_NAME: wikijs
    ports:
      - 3000:3000
  mariadb:
    image: mariadb:10.5
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wikijs
      MYSQL_USER: wikijs
      MYSQL_PASSWORD: wikijs
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

volumes:
  mariadb-data:
