schemaVersion: 2.0.0

commandTests:
  - name: apk exists
    command: "apk"
    args: ["--version"]
    exitCode: 0
    expectedOutput: ["apk-tools .*"]

fileExistenceTests:
  - name: apk repositories exists
    path: "/etc/apk/repositories"

fileContentTests:
  - name: alpine-release exists
    path: "/etc/alpine-release"
    expectedContents: ["[0-9]+[.][0-9]+[.][0-9]+"]

metadataTest:
  cmd: ["/bin/sh"]
