services:
  container-structure-test:
    image: ghcr.io/googlecontainertools/container-structure-test:latest
    command: ["test", "--pull", "--image", "alpine:latest", "--config", "config.yaml"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yaml:/config.yaml:ro
