services:
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9090"
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/data

volumes:
  minio-data:
