version: '3'

services:
  zookeeper:
    image: zookeeper:3.5
    ports:
      - 2181:2181
    network_mode: host
  kafka:
    image: wurstmeister/kafka:1.1.0
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CREATE_TOPICS: "test:2:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    volumes:
      - ./kafka:/kafka
    depends_on:
      - zookeeper
    network_mode: host
