version: '3'

services:
  zookeeper:
    image: zookeeper:3.5
    restart: always
    ports:
      - 2181:2181
    volumes:
      - zk-data:/data
      - zk-datalog:/datalog
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    restart: always
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:2:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka-data:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

volumes:
  zk-data:
  zk-datalog:
  kafka-data:
