version: "3"

services:
  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - 2003:2003
      - 8086:8086
    environment:
      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_USER: graphite
      INFLUXDB_USER_PASSWORD: graphite
    volumes:
      - influx-data:/var/lib/influxdb

volumes:
  influx-data:
