version: "3"

services:
  tempo:
    image: grafana/tempo:1.0.0
    ports:
      - 4317:4317
      - 6831:6831/udp
      - 6832:6832
      - 9411:9411
      - 14250:14250
      - 14268:14268
    volumes:
      - ./tempo-local.yaml:/etc/tempo-local.yaml:ro
    command: ["-config.file=/etc/tempo-local.yaml"]
