version: "3"

services:
  tempo:
    image: grafana/tempo:2.0.1
    ports:
      - 4317:4317
      - 6831:6831/udp
      - 6832:6832
      - 9411:9411
      - 14250:14250
      - 14268:14268
    volumes:
      - tempo-data:/tmp/tempo
      - ./tempo-local.yaml:/etc/tempo-local.yaml
    command: ["-config.file=/etc/tempo-local.yaml"]
  grafana:
    image: grafana/grafana:9.4.3
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    ports:
      - 3000:3000
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-data:/var/lib/grafana
    profiles:
      - grafana
  prometheus:
    image: prom/prometheus:v2.42.0
    command:
      - --config.file=/etc/prometheus.yaml
      - --enable-feature=exemplar-storage
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus.yaml
    ports:
      - 9090:9090
    profiles:
      - grafana
  loki:
    image: grafana/loki:2.7.4
    ports:
      - 3100:3100
    volumes:
      - loki-data:/loki
    profiles:
      - grafana

volumes:
  tempo-data:
  grafana-data:
  prometheus-data:
  loki-data:
