version: '3'

services:
  gogs:
    image: gogs/gogs:0.11.53
    restart: always
    ports:
    - 3000:3000
    volumes:
    - gogs-data:/data
    depends_on:
    - mariadb
  mariadb:
    image: mariadb:10.4
    restart: always
    volumes:
    - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: gogs
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

volumes:
  gogs-data:
  mariadb-data:
