services:
  gatling:
    image: denvazh/gatling:3.2.0
    volumes:
      - ./conf:/opt/gatling/conf:ro
      - ./results:/opt/gatling/results
      - ./user-files:/opt/gatling/user-files:ro
    network_mode: host
